[package]
name = "jex-sc-raffle-v-2-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.jex-sc-raffle-v-2]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.56.0"
default-features = false
