// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           17
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    jex_sc_raffle_v_2
    (
        init => init
        upgrade => upgrade
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
        pause => pause_endpoint
        unpause => unpause_endpoint
        isPaused => paused_status
        setFeesReceiver => set_fees_receiver_endpoint
        setProtocolFeePercent => set_protocol_fee_percent_endpoint
        setRaffleCreationFee => set_raffle_creation_fee_endpoint
        getFeesReceiver => fees_receiver
        getProtocolFeePercent => protocol_fee_percent
        getRaffleCreationFee => raffle_creation_fee
        getRaffles => get_raffles
        getRaffle => raffles
        getRaffleIdCounter => raffle_id_counter
        createRaffle => create_raffle_endpoint
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
